### ISSUE TITLE
two issues 

### ISSUE THREAD

**Issue by codebs** [willianmano/moodle-block_ranking#4]
(1) For activities with a full point over 10, say 100 points, if the teacher gives a student a mark of 70 points, ranking block just adds 2(completion mark) + 7=9 points. is there anyway to treat 70 as 70 instead of 7? 

(2) Within a course if the teacher messes up something with the ranking and try to be fair and wants to delete the ranking box , and starts the event listening from the scratch, after delete and add a new ranking block, the old points are still there, is there anyway to fix it ? 

Thanks for the great plugin.

**Comment by willianmano** [comment]
(1) I did it intentionally. You can change that on file the file class/manager.php and comment the lines 175 and 177.
(2) I never had thought about that, i can add a button like 'reset ranking points'. But completed activities will not add points again.

**Comment by codebs** [comment]
Thanks William for your reply 

As for (2), I think a reset button may be a valuable solution. Since messing up usually happens at the early stage of course preparation, especially when the teacher is trying some new activities or so. For now, there is no way to zero the points of all students except delete the account of the student and then let him in again(Even getting the students out of the course and enroll again will not work). 

Thanks again for the useful tool.
